name: qrcoder
description: Yet another stupid dart qrcode plugin.
version: 0.2.0
author: EyreFree
homepage: https://github.com/EyreFree/qrcoder

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.3